# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/motorola/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(BOARD_VENDOR),motorola)

include $(CLEAR_VARS)

NQ_NFC_SYMLINKS := $(TARGET_OUT_SYSTEM_EXT)/app/NQNfcNci/lib/arm64
$(NQ_NFC_SYMLINKS): $(LOCAL_INSTALLED_MODULE)
	@echo "Creating NQNfcNci symlinks: $@"
	@mkdir -p $@
	$(hide) ln -sf /system_ext/lib64/libsn100nfc_nci_jni.so $@/libsn100nfc_nci_jni.so

ALL_DEFAULT_INSTALLED_MODULES += $(NQ_NFC_SYMLINKS)

endif
