# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/felica/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/felica \
    vendor/nxp/opensource/interfaces/nfc \
    vendor/nxp/opensource/commonsys/external/libnfc-nci \
    vendor/nxp/opensource/commonsys/frameworks \
    vendor/nxp/opensource/commonsys/packages/apps/Nfc \
    vendor/nxp/opensource/sn100x/halimpl \
    vendor/nxp/opensource/sn100x/hidlimpl \
    vendor/nxp/nfc \
    vendor/nxp/secure_element \
    vendor/nxp/secure_element_extns

PRODUCT_PACKAGES += \
    NQNfcNci \
    libnqnfc-nci \
    libnqnfc_nci_jni \
    libsn100nfc_nci_jni \
    libsn100nfc-nci \
    com.nxp.nfc.nq \
    com.nxp.nfc.nq.xml \
    com.android.nfc_extras \
    vendor.nxp.hardware.nfc@2.0-service \
    nfc_nci.nqx.default.hw \
    se_nq_extn_client \
    ls_nq_client \
    jcos_nq_client
